package edu.umn.ncs

/** This class is used to easily archive out old selection
criteria queries for reference */
class BatchCreationQueryArchive implements Serializable {

	/** This is the SQL selection query used to choose
	what people, households or dwelling units will get
	the instrument(s) generated by this configuration. */
    String selectionQuery
	/** this is the date the query was archived */
    Date dateCreated = new Date()

	/** this is the default string converter for this class.
	It returns the date created. */
    String toString() {
        dateCreated.format('M/d/yyyy h:mm:ss a')
    }

	/** this static belongsTo map associates this class
	with the parent BatchCreationConfig that it belongs
	to throught the batchCreationConfig attribute */
    static belongsTo = [batchCreationConfig : BatchCreationConfig]

	/** This static defines any non-standard constraints
	placed on attributes with this class.
	<dl>
		<dt>selectionQuery</dt>
		<dd>optional (nullable), maximum length of 8000 characters</dd>
	</dl> */
    static constraints = {
        selectionQuery(maxSize:8000)
        dateCreated()
    }

	/** this static mapping sets the default sort order for this
	domain class to be sorted by the 'dateCreated' attribute. */
	static mapping = {
		sort 'dateCreated'
	}
}
